javascripts:
  jquery:
    - public/javascripts/jquery.js
    - public/javascripts/jquery_ujs.js

  application:
    - public/javascripts/application.js

stylesheets:
  application:
    - public/stylesheets/reset.css
    - public/stylesheets/common.css
    - public/stylesheets/application.css
    - public/stylesheets/scaffold.css
